# Generated by Django 6.0 on 2025-12-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_email_confirm_token_alter_usuario_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email_confirm_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica se o usuário deve ser tratado como ativo. Desmarque isso em vez de excluir contas.', verbose_name='ativo'),
        ),
    ]
