# Generated by Django 5.2.6 on 2025-12-11 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_CREATE', 'Criação de Usuário'), ('EVENT_CREATE', 'Cadastro de Evento'), ('EVENT_UPDATE', 'Alteração de Evento'), ('EVENT_DELETE', 'Exclusão de Evento'), ('EVENT_API_VIEW', 'Consulta de Evento via API'), ('CERTIFICATE_GENERATE', 'Geração de Certificado'), ('CERTIFICATE_VIEW', 'Consulta de Certificado'), ('ENROLL_CREATE', 'Inscrição em Evento')], max_length=50, verbose_name='Ação')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalhes da Ação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
    ]
