# Generated by Django 5.2.6 on 2025-12-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_evento_apresentador_alter_evento_nome_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, help_text='Upload de uma imagem para o banner do evento.', null=True, upload_to='event_banners/'),
        ),
    ]
